# Generated by Django 6.0.1 on 2026-01-26 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaoapp', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=50)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_analytics', to='zaoapp.order')),
            ],
            options={
                'ordering': ('-initiated_at',),
            },
        ),
    ]
